version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      source venv/bin/activate
      chmod +x ./scripts/fetch_dataset.sh ./scripts/credentials.sh

jobs:
  test_bigmart_model:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/project/packages/datacube_bigmart
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Installing Requirements
          command: |
            pip install -r requirements.txt
            python setup.py install --force
      - *fetch_data
      - run:
          name: Fetching data
          command: |
            ./scripts/fetch_dataset.sh
      - run:
          name: Running Tests for Bigmart Model
          command: |
            py.test -vv tests

  test_ml_api:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Installing Requirements
          command: |
            pip install -r packages/ml_api/requirements.txt
      - run:
          name: Running Tests for API
          command: |
            py.test -vv packages/ml_api/tests

  train_and_upload_bigmart_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Installing Requirements
          command: |
            pip install -r packages/datacube_bigmart/requirements.txt
      - *fetch_data
        - run:
            name: Fetching data
            command: |
              ./scripts/fetch_dataset.sh
      - run: 
          name: Publish model
          command: |
            . venv/bin/activate
            ./scripts/publish_retrain_package.sh

workflows:
  version: 2
  test-all:
    jobs:
      - test_bigmart_model
      - test_ml_api
      - train_and_upload_bigmart_model
      - test_ml_api:
          requires:
            - train_and_upload_bigmart_model
