version: 2
jobs:
  test_bigmart_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            ls -al
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r  packages/datacube_bigmart/requirements.txt
            chmod +x ./scripts/fetch_dataset.sh
            ./scripts/fetch_dataset.sh
            py.test -vv packages/datacube_bigmart/tests
workflows:
  version: 2
  test-all:
    jobs:
      - test_bigmart_model
